
root: /

Home: /
Archives: /archives
About: /about

language: en

author: fuzhouxx Dong
description: good good study day day up

github: https://github.com/fuzhouxxdong
email: fuzhouxxdong@gmail.com

favicon: /favicon.ico


# stylesheets loaded in the <head>
stylesheets:
- /css/hexo-theme-adoubi.min.css


