
root: /

menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about

language: en

author: Annie
description: good good study, day day up

favicon: /images/favicon.ico



